# Generated by Django 3.1.4 on 2021-03-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order_Received', 'Order_Received'), ('Order_Processing', 'Order_Processing'), ('On_The_Way', 'On_The_Way'), ('Order_Completed', 'Order_Completed'), ('Order_Canceled', 'Order_Canceled')], max_length=100),
        ),
    ]
