# Generated by Django 3.1.4 on 2021-03-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0002_auto_20210312_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Customer',
            new_name='customer',
        ),
    ]
